<?php

/**
 * @file entity_operations_test.module
 * Provides a test entity type for testing operations.
 */

/**
 * Implements hook_entity_operation_info().
 */
function entity_operations_test_entity_operation_info() {
  $info = array(
    'entity_operations_test' => array(
      'view' => array(
        'handler' => 'EntityOperationsOperationEntityView',
        'provision' => array(
          'menu' => array(
            'default' => TRUE,
            'menu item' => array(
              'title' => 'Main',
            ),
          ),
          'views field' => TRUE,
        ),
      ),
      'edit' => array(
        'handler' => 'EntityOperationsOperationEdit',
        'provision' => array(
          'menu' => TRUE,
          'views field' => TRUE,
        ),
      ),
      'add' => array(
        'handler' => 'EntityOperationsOperationAdd',
        'provision' => array(
          'menu' => TRUE,
        ),
      ),
      'delete' => array(
        'handler' => 'EntityOperationsOperationDelete',
        'provision' => array(
          'menu' => TRUE,
          'views field' => TRUE,
        ),
      ),
    ),
  );
  return $info;
}

/**
 * Implements hook_entity_info().
 */
function entity_operations_test_entity_info() {
  $return = array(
    'entity_operations_test' => array(
      'label' => t('Test Entity'),
      'plural label' => t('Test Entities'),
      'description' => t('An entity type used by the Entity Operations tests.'),
      'entity class' => 'Entity',
      'controller class' => 'EntityAPIController',
      'base table' => 'entity_operations_test',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'eid',
        'bundle' => 'type',
        'label' => 'title',
      ),
      'label callback' => 'callback_entity_info_label',
      'uri callback' => 'entity_operations_entity_uri',
      'operations ui' => array(
        'path' => 'entity_operations_test',
      ),
      'access callback' => 'entity_operations_test_access',
      'bundles' => array(
        // Provide two bundles so we can test bundle-related things.
        'alpha' => array(
          'label' => t('Alpha'),
        ),
        'beta' => array(
          'label' => t('Beta'),
        ),
      ),
      'module' => 'entity_operations_test',
      // Admin UI for our 'add' and 'edit' operations.
      // TODO: check if actually needed!
      'admin ui' => array(
        'file' => 'entity_operations_test.admin.inc',
      ),
    ),
  );

  return $return;
}

/**
 * Implements callback_entity_info_label().
 */
function callback_entity_info_label($entity, $entity_type) {
  return empty($entity->title) ? 'Untitled entity' : $entity->title;
}

/**
 * Entity API access callback.
 */
function entity_operations_test_access($op, $entity, $account, $entity_type) {
  // TODO!
  return TRUE;
}
